# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - MyEpicWebSiteByErIComparan

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://mcr.mihttps://myepicwebsitebyericomparan.azurewebsites.netcrosoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_13cfca9f08a74f1db982baade1ac76db }}
        password: ${{ secrets.AzureAppService_ContainerPassword_2b922844d1694f87a453c525f2de2c28 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: mcr.mihttps://myepicwebsitebyericomparan.azurewebsites.netcrosoft.com/${{ secrets.AzureAppService_ContainerUsername_13cfca9f08a74f1db982baade1ac76db }}/appsvc/wordpress-alpine-php:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'MyEpicWebSiteByErIComparan'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_1936ee8af4c841b4ae89e3a5386fed9c }}
        images: 'mcr.mihttps://myepicwebsitebyericomparan.azurewebsites.netcrosoft.com/${{ secrets.AzureAppService_ContainerUsername_13cfca9f08a74f1db982baade1ac76db }}/appsvc/wordpress-alpine-php:${{ github.sha }}'